// Compatibility barrel: callers keep importing all domain APIs and DTOs from "@/lib/api".
export { setToken, getToken, clearToken, getApiBase, resolveMediaUrl } from "./api-client"
export { authApi } from "./api/auth"
export type { UserLoginResponse, CurrentUserResponse } from "./api/auth"
export { userApi, roleApi, appUserApi } from "./api/users"
export type { UserListQueryParams, PermissionNode, RoleCreateDto, RoleUpdateDto, AppUserDetail } from "./api/users"
export { appApi } from "./api/apps"
export type { MonetizationType, AppListItem, AppCreateDto, AppUpdateDto } from "./api/apps"
export { promotionLinkApi } from "./api/promotion"
export type { PromotionLinkListItem, PromotionLinkCreateDto, PromotionLinkCreateResult } from "./api/promotion"
export { dramaApi, episodeApi, uploadApi } from "./api/dramas"
export type { DramaCreateDto, EpisodeItem } from "./api/dramas"
export { subscriptionApi, paymentConfigApi } from "./api/monetization"
export type { SubscriptionPlanCreateDto, SubscriptionPlanItem, PaymentConfigCreateDto, PaymentConfigItem } from "./api/monetization"
export { rechargeOrderApi, adSessionApi, mediaEventReportApi } from "./api/operations"
export type { RechargeOrderItem, AdSessionItem, MediaEventReportItem } from "./api/operations"
